#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.htjy.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://42.192.226.123:12986/htjy
    username: root
    password: gGh$5G&3dfFGDGDff
    driver-class-name: com.mysql.cj.jdbc.Driver