
#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.htjy.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:33306/htjy
    username: htjy
    password: gGh$5ojkGDGDff
    driver-class-name: com.mysql.cj.jdbc.Driver